language: go
dist: bionic
go:
  - 1.13.x

matrix:
  include:
    - name: test
      script:
        - make test
    - name: race
      script:
        - make race
    - name: fmt
      script:
        - make fmt
        - git diff --exit-code
